language: ruby
 - sudo apt-get update
 - sudo apt-get install cmake
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.1
  - 2.2.2
  - 2.2.3
script: bundle exec rspec
cache: bundler